### ISSUE TITLE
Das Open-Data-Portal der Stadt Münster hat eine neue URL

### ISSUE THREAD

**Issue by tomsrocket** [tursics/open-data-atlas#51]
Hallo, die Adresse des Open-Data-Portals von Münster ist nicht mehr korrekt, die neue Url lautet: https://opendata.stadt-muenster.de/
Ich habe dazu einen Pull-Request gestellt, kannst Du den bitte mergen, oder die Url bitte korrigieren, danke!

**Comment by tursics** [comment]
Danke für den Hinweis. Ich habe die neue Adresse eingefügt. Der aktualisierte Datensatz ist seit Ende Juni unter https://www.offenesdatenportal.de/dataset/ubersicht-der-open-data-angebote-in-deutschland/resource/2a8fafd0-b87f-4342-82b6-6e56569d673d erreichbar.

Die Darstellung auf der Karte muss noch geändert werden.

Danke,
Thomas
